# SETS KE LIYE CURLY BRACES KA USE HOTA HAI.
# SETS MEIN HAM KISI V TYPE KE DATA TYPE KO STORE KR SKTE HAI 

# EMPTY SET BANANAE KE LIYE METHOD
s = set()
print(type(s))

# EMPTY SET BANANE KE LIYE HAM {} USE NHI KR SKTE BECAUSE YE AIISA KRNE PAR EK EMPTY DICTIONARY CREATE KR DEGA.
# NO REPETITION ALLOWED IN SET

# SETS ARE UNORDERED , UNINDEXED .
# THERE IS NO WAY TO CHANGE ITEMS IN SET.
# 
